export enum CompanyBasicInfoComponentsNames {
  LBL_COMPANY_NAME = "lblCompanyName",
  TXT_COMPANY_NAME = "txtCompanyName",
  LBL_LEGAL_NAME = "lblLegalName",
  TXT_LEGAL_NAME = "txtLegalName",
  LBL_BUS_LICENSE = "lblBusLicense",
  TXT_BUS_LICENSE = "txtBusLicense",
  LBL_TAX_ID = "lblTaxID",
  TXT_TAX_ID = "txtTaxID",
  LBL_IATA = "lblIATA",
  TXT_IATA = "txtIATA",
  LBL_COMPANY_CATEGORY = "lblCompanyCategory",
  SEL_COMPANY_CATEGORY = "selCompanyCategory",
  LBL_COMPANY_TYPE = "lblCompanyType",
  SEL_COMPANY_TYPE = "selCompanyType",
}

/* --------------------- Enums For Label Task --------------------*/
export enum PersonBasicInfoLabels {
  // -----------------------------------------    DelReg = 16     -------------------------------------
  LBL_LOGIN_ID = "lblLoginId",
  LBL_CHANGE_PASSWORD = "lblChangePassword",
  LBL_PAGE_TITLE = "PageTitle",
  LBL_FIRST_NAME = "FirstNameLabel",
  LBL_MIDDLE_NAME = "MiddleNameLabel",
  LBL_LAST_NAME = "LastNameLabel",
  LBL_SUFFIX = "SuffixLabel",
  LBL_TITLE = "TitleLabel",
  LBL_INFORMAL = "InformalNameLabel",
  LBL_SALUTATION = "SalutationLabel",
  LBL_DESIGNATION = "DesignationLabel",
  LBL_GENDER = "GenderLabel",
  CMB_GENDER = "cmbGender",
  // ----------------------------------------- DelEventInfo = 24 -------------------------------------
  LBL_DIETARY = "DietaryLabel",
  LBL_SPECIAL_NEEDS = "SpecNeedsLabel",
  LBL_PREF_SEAT = "PrefSeatLabel",
  LBL_ALLERGIES = "Allergies",
  LBL_EMERGENCY_PHONE = "EmergencyPhone",
  LBL_EMERGENCY_CONTACT = "EmergencyContact",
  LBL_OTHER_DIETARY = "OtherDietaryLabel",
  // ---------------------------------------- Useless || Not Found -----------------------------------
  LBL_PERSON_FLAG = "PerConFlagLabel",
  BTN_COPY_PUBLIC_COMP_INFO_IN_PERSON = "lblCopyPublicCompInfoInPerson",
  BTN_LINK_ALL_TOOLTIP_TEXT = "LinkAllLabel",
  LBL_DEL_NAME_LABEL = "DelNameLabel",
  LBL_ALT_COMP_NAME = "AltCompLabel",
  LBL_DEL_NAME = "lblDelName",
}
export enum companyInformationLabels {
  LBL_PAGE_TITLE = "PageTitle",
  LBL_COMPANY_NAME = "CompanyNameLabel",
  LBL_LEGAL_NAME = "LegalNameLabel",
  LBL_BUS_LICENSE = "BusLicenseLabel",
  LBL_TAX_ID = "TaxIDLabel",
  LBL_IATA = "IATALabel",
  LBL_COMPANY_CATEGORY = "lblCompanyCategory",
  LBL_COMPANY_TYPE = "CompanyTypeLabel",
  BTN_LINK_ALL_TOOLTIP_TEXT = "LinkAllLabel",
}
export enum commInfoLabels {
  LBL_ADDRESS = "AddressLabel",
  LBL_CITY = "CityLabel",
  LBL_STATE = "StateLabel",
  LBL_COUNTRY = "CountryLabel",
  LBL_POSTAL_CODE = "PostalCodeLabel",
  LBL_PHONE = "PhoneLabel",
  LBL_NUMBER_AREA = "NumberAreaLabel",
  LBL_NUMBER_EXT = "NumberExtLabel",
  LBL_FAX = "FaxLabel",
  LBL_MOBILE = "MobileLabel",
  LBL_TOLL_FREE = "TollFreeLabel",
  LBL_EMAIL = "EmailLabel",
  LBL_WEBSITE = "WebSiteLabel",
  LBL_NUMBER = "NumberLabel",
}
/* --------------------- END ------------------------------------*/

export enum PersonBasicInfoComponentsNames {
  // -----------------------------------------    DelReg = 16     -------------------------------------
  LBL_LOGIN_ID = "lblLoginID",
  TXT_LOGIN_ID = "txtLoginID",
  TXT_PASSWORD = "txtPassword",
  LBL_FIRST_NAME = "lblFirstName",
  TXT_FIRST_NAME = "txtFirstName",
  LBL_MIDDLE_NAME = "lblMiddle",
  TXT_MIDDLE_NAME = "txtMiddle",
  LBL_LAST_NAME = "lblLastName",
  TXT_LAST_NAME = "txtLastName",
  LBL_SUFFIX = "lblSuffix",
  TXT_SUFFIX = "txtSuffix",
  LBL_TITLE = "lblTitle",
  TXT_TITLE = "txtTitle",
  LBL_INFORMAL = "lblInformal",
  TXT_INFORMAL = "txtInformal",
  LBL_SALUTATION = "lblSalutation",
  TXT_SALUTATION = "txtSalutation",
  LBL_DESIGNATION = "lblDesignation",
  TXT_DESIGNATION = "txtDesignation",
  LBL_GENDER = "lblGender",
  CMB_GENDER = "cmbGender",
  // ----------------------------------------- DelEventInfo = 24 -------------------------------------
  LBL_DIETARY = "lblDietary",
  MLT_DIETARY = "mltDietary",

  LBL_SPECIAL_NEEDS = "lblSpecNeeds",
  MLT_SPECIAL_NEEDS = "mltSpecNeeds",

  LBL_PREF_SEAT = "lblPrefSeat",
  CMB_PREF_SEAT = "cmbPrefSeat",

  LBL_ALLERGIES = "lblAllergies",
  TXT_ALLERGIES = "txtAllergies",

  LBL_EMERGENCY_PHONE = "lblEmerPhone",
  TXT_EMERGENCY_PHONE = "txtEmerPhone",

  LBL_EMERGENCY_CONTACT = "lblEmerContact",
  TXT_EMERGENCY_CONTACT = "txtEmerContact",

  LBL_OTHER_DIETARY = "lblOtherDietary",
  TXT_OTHER_DIETARY = "txtOtherDietary",
  // ---------------------------------------- Useless || Not Found -----------------------------------
  LBL_PERSON_FLAG = "lblPerConFlag",
  CMB_PERSON_FLAG = "cmbPerConFlag",
  BTN_COPY_PUBLIC_COMP_INFO_IN_PERSON = "btnCopyPublicCompInfoInPerson",
  LBL_DEL_NAME_LABEL = "lblDelNameLabel",
  LBL_ALT_COMP_NAME = "lblAltCompName",
  LBL_DEL_NAME = "lblDelName",
}
export enum CommInfoComponentsNames {
  LBL_COMM_TYPES = "lblCommTypes",
  CLIP_CONTENT_CLIP_ADDRESS = "clipContent.clipAddress",
  CLIP_CONTENT_CLIP_ADDRESS_LBL_ADDRESS = "clipContent.clipAddress.lblAddress",
  CLIP_CONTENT_CLIP_ADDRESS_TXT_ADDRESS1 = "clipContent.clipAddress.txtAddress1",
  CLIP_CONTENT_CLIP_ADDRESS_TXT_ADDRESS2 = "clipContent.clipAddress.txtAddress2",
  CLIP_CONTENT_CLIP_ADDRESS_LBL_POSTAL_CODE = "clipContent.clipAddress.lblPostalCode",
  CLIP_CONTENT_CLIP_ADDRESS_TXT_POSTAL_CODE = "clipContent.clipAddress.txtPostalCode",
  CLIP_CONTENT_CLIP_ADDRESS_LBL_CITY = "clipContent.clipAddress.lblCity",
  CLIP_CONTENT_CLIP_ADDRESS_TXT_CITY = "clipContent.clipAddress.txtCity",
  CLIP_CONTENT_CLIP_ADDRESS_LBL_COUNTRY = "clipContent.clipAddress.lblCountry",
  CLIP_CONTENT_CLIP_ADDRESS_TXT_COUNTRY = "clipContent.clipAddress.txtCountry",
  CLIP_CONTENT_CLIP_ADDRESS_LBL_STATE = "clipContent.clipAddress.lblState",
  CLIP_CONTENT_CLIP_ADDRESS_TXT_STATE = "clipContent.clipAddress.txtState",
  CLIP_CONTENT_CLIP_LABELS = "clipContent.clipLabels",
  CLIP_CONTENT_CLIP_LABELS_LBL_NUMBER_COUNTRY = "clipContent.clipLabels.lblNumberCountry",
  CLIP_CONTENT_CLIP_LABELS_LBL_NUMBER_CODE = "clipContent.clipLabels.lblNumberCode",
  CLIP_CONTENT_CLIP_LABELS_LBL_NUMBER_AREA = "clipContent.clipLabels.lblNumberArea",
  CLIP_CONTENT_CLIP_LABELS_LBL_NUMBER = "clipContent.clipLabels.lblNumber",
  CLIP_CONTENT_CLIP_LABELS_LBL_NUMBER_EXT = "clipContent.clipLabels.lblNumberExt",
  CLIP_CONTENT_CLIP_PHONE = "clipContent.clipPhone",
  CLIP_CONTENT_CLIP_PHONE_LBL_NUMBER_TYPE = "clipContent.clipPhone.lblNumberType",
  CLIP_CONTENT_CLIP_PHONE_TXT_COUNTRY = "clipContent.clipPhone.txtCountry",
  CLIP_CONTENT_CLIP_PHONE_TXT_NUMBER_CODE = "clipContent.clipPhone.txtNumberCode",
  CLIP_CONTENT_CLIP_PHONE_TXT_NUMBER_AREA = "clipContent.clipPhone.txtNumberArea",
  CLIP_CONTENT_CLIP_PHONE_TXT_NUMBER = "clipContent.clipPhone.txtNumber",
  CLIP_CONTENT_CLIP_PHONE_TXT_NUMBER_EXT = "clipContent.clipPhone.txtNumberExt",
  CLIP_CONTENT_CLIP_PHONE_LINKED_CHK = "clipContent.clipPhone.LenkedChk",
  CLIP_CONTENT_CLIP_FAX = "clipContent.clipFax",
  CLIP_CONTENT_CLIP_FAX_LBL_NUMBER_TYPE = "clipContent.clipFax.lblNumberType",
  CLIP_CONTENT_CLIP_FAX_TXT_COUNTRY = "clipContent.clipFax.txtCountry",
  CLIP_CONTENT_CLIP_FAX_TXT_NUMBER_CODE = "clipContent.clipFax.txtNumberCode",
  CLIP_CONTENT_CLIP_FAX_TXT_NUMBER_AREA = "clipContent.clipFax.txtNumberArea",
  CLIP_CONTENT_CLIP_FAX_TXT_NUMBER = "clipContent.clipFax.txtNumber",
  CLIP_CONTENT_CLIP_FAX_TXT_NUMBER_EXT = "clipContent.clipFax.txtNumberExt",
  CLIP_CONTENT_CLIP_FAX_TXT_LINKED_CHK = "clipContent.clipFax.LenkedChk",
  CLIP_CONTENT_CLIP_TOLL_FREE = "clipContent.clipTollFree",
  CLIP_CONTENT_CLIP_TOLL_FREE_LBL_COUNTRY = "clipContent.clipTollFree.lblCountry",
  CLIP_CONTENT_CLIP_TOLL_FREE_LBL_NUMBER_CODE = "clipContent.clipTollFree.lblNumberCode",
  CLIP_CONTENT_CLIP_TOLL_FREE_LBL_NUMBER_CIT = "clipContent.clipTollFree.lblNumberCity",
  CLIP_CONTENT_CLIP_TOLL_FREE_LBL_NUMBER = "clipContent.clipTollFree.lblNumber",
  CLIP_CONTENT_CLIP_TOLL_FREE_LBL_NUMBER_TYPE = "clipContent.clipTollFree.lblNumberType",
  CLIP_CONTENT_CLIP_TOLL_FREE_TXT_COUNTRY = "clipContent.clipTollFree.txtCountry",
  CLIP_CONTENT_CLIP_TOLL_FREE_TXT_NUMBER_CODE = "clipContent.clipTollFree.txtNumberCode",
  CLIP_CONTENT_CLIP_TOLL_FREE_TXT_NUMBER_AREA = "clipContent.clipTollFree.txtNumberArea",
  CLIP_CONTENT_CLIP_TOLL_FREE_TXT_NUMBER = "clipContent.clipTollFree.txtNumber",
  CLIP_CONTENT_CLIP_TOLL_FREE_TXT_NUMBER_EXT = "clipContent.clipTollFree.txtNumberExt",
  CLIP_CONTENT_CLIP_TOLL_FREE_TXT_LINKED_CHK = "clipContent.clipTollFree.LenkedChk",
  CLIP_CONTENT_CLIP_MOBILE = "clipContent.clipMobile",
  CLIP_CONTENT_CLIP_MOBILE_LBL_NUMBER_TYPE = "clipContent.clipMobile.lblNumberType",
  CLIP_CONTENT_CLIP_MOBILE_TXT_COUNTRY = "clipContent.clipMobile.txtCountry",
  CLIP_CONTENT_CLIP_MOBILE_TXT_NUMBER_CODE = "clipContent.clipMobile.txtNumberCode",
  CLIP_CONTENT_CLIP_MOBILE_TXT_NUMBER_AREA = "clipContent.clipMobile.txtNumberArea",
  CLIP_CONTENT_CLIP_MOBILE_TXT_NUMBER = "clipContent.clipMobile.txtNumber",
  CLIP_CONTENT_CLIP_MOBILE_TXT_NUMBER_EXT = "clipContent.clipMobile.txtNumberExt",
  CLIP_CONTENT_CLIP_MOBILE_TXT_LINKED_CHK = "clipContent.clipMobile.LenkedChk",
  CLIP_CONTENT_CLIP_EMAIL = "clipContent.clipEmail",
  CLIP_CONTENT_CLIP_EMAIL_LBL_EMAIL = "clipContent.clipEmail.lblEmail",
  CLIP_CONTENT_CLIP_EMAIL_TXT_EMAIL = "clipContent.clipEmail.txtEmail",
  CLIP_CONTENT_CLIP_EMAIL_LBL_VERIFY_EMAIL = "clipContent.clipEmail.lblVerifyEmail",
  CLIP_CONTENT_CLIP_EMAIL_TXT_VERIFY_EMAIL = "clipContent.clipEmail.txtVerifyEmail",
  CLIP_CONTENT_CLIP_URL = "clipContent.clipUrl",
  CLIP_CONTENT_CLIP_URL_LBL_WEBSITE = "clipContent.clipUrl.lblWebsite",
  CLIP_CONTENT_CLIP_URL_TXT_WEBSITE = "clipContent.clipUrl.txtWebsite",
}
export enum OtherComponentsNames {
  CLIP_BUTTON_LIST_NO_LINK = "clipButtonListNoLink",
  CLIP_LINK_ALL = "clipLinkAll",
  CLIP_BUTTON_LIST = "clipButtonList",
  CLIP_CONTENT = "clipContent",
  CLIP_LINK_ALL_CHK_LINK_ALL = "clipLinkAll.chkLinkAll",
  CLIP_LINK_ALL_LBL_LINK_ALL = "clipLinkAll.lblLinkAll",
  CLIP_CONTENT_CLIP_LINK = "clipContent.clipLink",
  CLIP_CONTENT_CLIP_LINK_LBL_LINK = "clipContent.clipLink.lblLink",
  CLIP_CONTENT_CLIP_LINK_CMB_LINK = "clipContent.clipLink.cmbLink",
  CLIP_BORDER = "clipBorder",
  CLIP_POPUP = "clipPopup",
  LBL_ADDITIONAL_INSTRUCTIONS = "lblAdditionalInstructions",
  CMB_LANGUAGE_PREFERENCE = "cmblanguagePreference",
  LBL_LANGUAGE_PREFERENCE = "lbllanguagePreference",
}
